[package]
name = "unitore"
version = "0.1.0"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>"
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/unitore"
description = """
Feed reader with the ability to set updates frequency.
"""
categories = [ "development-tools" ]
keywords = [ "rss-feed", "atom-feed" ]
repository = "https://github.com/Wandalen/wTools/tree/alpha/module/move/unitore"

# [lints]
# workspace = true

[package.metadata.docs.rs]
features = [ "full" ]

[features]
default = [
  "enabled",
]
full = [
  "enabled",
]
enabled = []

[dependencies]
error_tools = { workspace = true, features = [ "default" ] }
pth = { workspace = true, features = [ "default" ] }
tokio = { version = "1.36.0", features = [ "rt", "rt-multi-thread", "io-std", "macros" ] }
hyper = { version = "1.1.0", features = [ "client" ] }
hyper-tls = "0.6.0"
hyper-util = { version = "0.1", features = [ "client", "http2", "http1" ] }
http-body-util = "0.1"
feed-rs = "1.4.0"
toml = "0.8.10"
serde = "1.0.196"
url = { version = "2.0", features = ["serde"] }
humantime-serde = "1.1.1"
gluesql = "0.16.2"
async-trait = "0.1.41"
wca = { workspace = true }
mockall = "0.12.1"
cli-table = "0.4.7"
textwrap = "0.16.1"

[dev-dependencies]
test_tools = { workspace = true }

