[package]
name = "assistant"
version = "0.1.0"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/assistant"
repository = "https://github.com/Wandalen/wTools/tree/master/module/core/assistant"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/core/assistant"
description = """
Assist AI in writing code.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]
default-run = "main"

[lints]
workspace = true

[package.metadata.docs.rs]
features = [ "full" ]
all-features = false

[features]
default = [ "enabled" ]
full = [ "enabled" ]
enabled = [
  "former/enabled",
  "format_tools/enabled",
  "reflect_tools/enabled",
]

[[bin]]
name = "main"
path = "src/bin/main.rs"

[[bin]]
name = "list_resources"
path = "src/bin/list_resources.rs"

[dependencies]
# xxx : qqq : optimze features
mod_interface = { workspace = true, features = [ "full" ] }
former = { workspace = true, features = [ "full" ] }
format_tools = { workspace = true, features = [ "full" ] }
reflect_tools = { workspace = true, features = [ "full" ] }
openai-api-rs = { version = "=5.0.11" }
tokio = { version = "1", features = ["full"] }
dotenv = "0.15"
clap = { version = "4.5.20", features = ["derive"] }
pth = "0.21.0"
serde = { version = "1.0.213", features = ["derive"] }
serde_with = "3.11.0"
error_tools = "0.17.0"
derive_tools = { version = "0.32.0", features = ["full"] }

[dev-dependencies]
test_tools = { workspace = true }
