[package]
name = "variadic_from"
version = "0.24.0"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Dmytro Kryvoruchko <dmytro.kr@obox.systems>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/variadic_from"
repository = "https://github.com/Wandalen/wTools/tree/master/module/core/variadic_from"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/core/variadic_from"
description = """
Variadic from.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

[lints]
workspace = true

[package.metadata.docs.rs]
features = [ "full" ]
all-features = false



[features]

default = [
  "enabled",
  "derive_variadic_from",
  "type_variadic_from",
]

full = [
  "enabled",
  "derive_variadic_from",
  "type_variadic_from",
]
no_std = []
use_alloc = [ "no_std" ]
enabled = []

type_variadic_from = []
derive_variadic_from = [ "type_variadic_from", "derive_tools_meta/derive_variadic_from" ]

[dependencies]

## internal
derive_tools_meta = { workspace = true, features = [ "enabled", "derive_variadic_from" ] }

[dev-dependencies]
test_tools = { workspace = true }
