[package]
name = "deterministic_rand"
version = "0.5.0"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Viktor Dudnik <viktor.d@obox.systems>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/deterministic_rand"
repository = "https://github.com/Wandalen/wTools/tree/master/module/core/deterministic_rand"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/core/deterministic_rand"
description = """
Hierarchical random number generators for concurrent simulations with switchable determinism.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

[lints]
workspace = true

[package.metadata.docs.rs]
features = [ "full" ]
all-features = false
# exclude = [ "/tests", "/examples", "-*" ]

[features]
default = [ "enabled", "determinism" ]
full = [ "enabled", "determinism" ]
no_std = []
use_alloc = [ "no_std" ]
enabled = []
determinism = [ "rand_chacha", "rand_seeder", "iter_tools" ]

[dependencies]
mod_interface = { workspace = true, features = [ "default" ] }
iter_tools = { workspace = true, features = [ "default" ], optional = true }
rand = "0.8.5"
rand_chacha = { version = "0.3.1", optional = true }
rand_seeder = { version = "0.2.3", optional = true }
sealed = "0.5.0"

[dev-dependencies]
test_tools = { workspace = true }
rayon = "1.8.0"

[[example]]
name = "sample_deterministic_rand_trivial"
path = "examples/deterministic_rand_trivial.rs"
