[package]
name = "plot_interface"
version = "0.1.3"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Dmytro Kryvoruchko <dmytro.kr@obox.systems>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/plot_interface"
repository = "https://github.com/Wandalen/wTools/tree/master/module/core/plot_interface"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/core/plot_interface"
description = """
Plot interface.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

[lints]
workspace = true

[package.metadata.docs.rs]
features = [ "full" ]
all-features = false
# exclude = [ "/tests", "/examples", "-*" ]
include = [
  "/rust/impl/_blank",
  "/Cargo.toml",
  "/Readme.md",
  "/License",
]

[features]
default = [ "enabled" ]
full = [ "enabled" ]
no_std = []
use_alloc = [ "no_std" ]
enabled = []

[lib]
name = "plot_interface"
path = "src/plot/plot_interface_lib.rs"

[[test]]
name = "plot_interface_test"
path = "tests/plot/plot_interface_tests.rs"

# [lib]
# name = "plot_interface"
# path = "src/_blank/standard_lib.rs"
#
# [[test]]
# name = "plot_interface_test"
# path = "tests/_blank/tests.rs"

[[test]]
name = "plot_interface_smoke_test"
path = "tests/smoke_test.rs"

# [[example]]
# name = "plot_interface_trivial"
# path = "examples/plot_interface_trivial/src/main.rs"

[dependencies]
wplot = { workspace = true }

[dev-dependencies]
test_tools = { workspace = true }
