[package]
name = "macro_tools"
version = "0.38.0"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Dmytro Kryvoruchko <dmytro.kr@obox.systems>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/macro_tools"
repository = "https://github.com/Wandalen/wTools/tree/master/module/core/macro_tools"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/core/macro_tools"
description = """
Tools for writing procedural macroses.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose", "builder-pattern" ]

[lints]
workspace = true

[package.metadata.docs.rs]
features = [ "full" ]
all-features = false


[features]
default = [
  "enabled",
  "attr",
  "attr_prop",
  "components",
  "ct",
  "container_kind",
  "derive",
  "diag",
  "equation",
  "generic_args",
  "generic_params",
  "item",
  "item_struct",
  "name",
  "kw",
  "phantom",
  "punctuated",
  "quantifier",
  "struct_like",
  "tokens",
  "typ",
  "typed",
]
full = [
  "default",
]

enabled = [
  "default",
  "former_types/enabled",
  "interval_adapter/enabled",
  "clone_dyn_types/enabled",
  "iter_tools/enabled",
]

attr = [ "diag", "quantifier" ]
attr_prop = [ "components" ]
components = []
ct = []
container_kind = [ "typ" ]
derive = []
diag = []
equation = []
generic_args = []
generic_params = [ "punctuated" ]
item = [ "punctuated" ]
item_struct = []
iter = []
name = []
kw = []
phantom = [ "item" ]
punctuated = []
quantifier = []
struct_like = [ "item_struct" ]
tokens = []
typ = []
typed = []

# qqq : put all files under features: macro_attr, macro_container_kind, ...
# qqq : optimize features list
# qqq : make sure all combinations of features are working and passing test

# qqq : expose features
# syn_derive
# syn_parsing
# syn_printing
# syn_clone

[dependencies]

## external
proc-macro2 = { version = "~1.0.78", features = [] }
quote = { version = "~1.0.35", features = [] }
syn = { version = "~2.0.52", features = [ "full", "extra-traits" ] }
const_format = { version = "0.2.32", features = [] }

## internal
interval_adapter = { workspace = true, features = [] }
iter_tools = { workspace = true, features = [ "iter_trait" ] }
clone_dyn_types = { workspace = true, features = [] }
former_types = { workspace = true, features = [ "types_component_assign" ] }

[dev-dependencies]
test_tools = { workspace = true }
