[package]
name = "program_tools"
version = "0.1.0"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/program_tools"
repository = "https://github.com/Wandalen/wTools/tree/master/module/core/program_tools"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/core/program_tools"
description = """
Compile and run a Rust program.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

[lints]
workspace = true


[package.metadata.docs.rs]
features = [ "full" ]
all-features = false


[features]
default = [
  "enabled",
]
full = [
  "enabled"
 ]

enabled = [
  "mod_interface/enabled",
  "former/enabled",
  "proper_path_tools/enabled",
  "error_tools/enabled",
  "iter_tools/enabled",
]

[dependencies]
mod_interface = { workspace = true }
former = { workspace = true, features = [ "derive_former" ] }
proper_path_tools = { workspace = true }
error_tools = { workspace = true, features = [ "error_for_app" ] } # qqq : xxx : rid off error_for_app
iter_tools = { workspace = true }

# ## external
# duct = "0.13.7"


[dev-dependencies]
test_tools = { workspace = true }
# assert_fs = { version = "1.1.1" }
