[package]
name = "format_tools"
version = "0.1.0"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/format_tools"
repository = "https://github.com/Wandalen/wTools/tree/master/module/core/format_tools"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/core/format_tools"
description = """
Collection of mechanisms for formatting and serialization into string.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

[lints]
workspace = true

[package.metadata.docs.rs]
features = [ "full" ]
all-features = false

[features]

default = [
  "enabled",
]

full = [
  "enabled",
]
enabled = [
  "reflect_tools/enabled",
  # "derive_tools/enabled",
  "former/enabled",
]

[dependencies]
# derive_tools = { workspace = true, features = [ "derive_from", "derive_inner_from" ] }
reflect_tools = { workspace = true, features = [ "reflect_types" ] }
former = { workspace = true, features = [ "full" ] }
# qqq : xxx : optmize set of features

[dev-dependencies]
test_tools = { workspace = true }

# [build-dependencies]
# cfg_aliases = "0.1.1"
