[package]
name = "graphs_tools"
version = "0.3.0"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/graphs_tools"
repository = "https://github.com/Wandalen/wTools/tree/master/module/core/graphs_tools"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/core/graphs_tools"
description = """
Graphs tools.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

[lints]
workspace = true

[package.metadata.docs.rs]
features = [ "full" ]
all-features = false

[features]
default = [
  "enabled",
  "debug",
]
full = [
  "default",
]
enabled = [
  "meta_tools/enabled",
  "iter_tools/enabled",
  # "data_type/enabled",
  # "strs_tools/enabled",
  "collection_tools/enabled",
  "former/enabled",
]
debug = []

[dependencies]
# indexmap = "~1.8"
meta_tools = { workspace = true, features = [ "default" ] }
iter_tools = { workspace = true, features = [ "default" ] }
# data_type = { workspace = true, features = [ "default" ] }
collection_tools = { workspace = true, features = [ "default" ] }
# strs_tools = { workspace = true, features = [ "default" ] }
derive_tools = { workspace = true, features = [ "default" ] }
# type_constructor ={ workspace = true, features = [ "default" ] }
former = { workspace = true, features = [ "default" ] }

[dev-dependencies]
test_tools = { workspace = true }
