[package]
name = "test_tools"
version = "0.10.0"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
  "Dmytro Kryvoruchko <dmytro.kr@obox.systems>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/test_tools"
repository = "https://github.com/Wandalen/wTools/tree/master/module/core/test_tools"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/core/test_tools"
description = """
Tools for writing and running tests.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose", "testing" ]

[lints]
workspace = true

[package.metadata.docs.rs]
features = [ "full" ]
all-features = false



# = features

[features]
default = [ "enabled" ]
full = [ "enabled" ]
no_std = [
  # "error_tools/no_std",
  # "meta_tools/no_std",
  # "mem_tools/no_std",
  # "typing_tools/no_std",
  # "data_type/no_std",
  # "diagnostics_tools/no_std",
  # "process_tools_published/no_std",
  # "former_stable/use_alloc",
]
use_alloc = [
  "no_std",
  # "error_tools/use_alloc",
  # "meta_tools/use_alloc",
  # "mem_tools/use_alloc",
  # "typing_tools/use_alloc",
  # "data_type/use_alloc",
  # "diagnostics_tools/use_alloc",
  # "process_tools_published/use_alloc",
  # "former_stable/use_alloc",
]
enabled = [
  "error_tools/enabled",
  "meta_tools/enabled",
  "mem_tools/enabled",
  "typing_tools/enabled",
  "data_type/enabled",
  "diagnostics_tools/enabled",
  "process_tools/enabled",
  "collection_tools/enabled",
]
# nightly = [ "typing_tools/nightly" ]

[dependencies]

## external

paste = "~1.0" # zzz : remove laster
rustversion = "~1.0"
# anyhow = "~1.0"
num-traits = "~0.2"
trybuild = { version = "1.0.85", features = [ "diff" ] }
rand = "0.8.5"

## internal

error_tools = { workspace = true, features = [ "full" ] }
meta_tools = { workspace = true, features = [ "full" ] }
mem_tools = { workspace = true, features = [ "full" ] }
typing_tools = { workspace = true, features = [ "full" ] }
data_type = { workspace = true, features = [ "full" ] }
diagnostics_tools = { workspace = true, features = [ "full" ] }
process_tools = { workspace = true, features = [ "full" ] }
collection_tools = { workspace = true, features = [ "full" ] }
# former_stable = { workspace = true, features = [ "full" ] }

[build-dependencies]
rustc_version = "0.4"
