[package]
name = "reflect_tools_meta"
version = "0.2.0"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>",
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/reflect_tools_meta"
repository = "https://github.com/Wandalen/wTools/tree/master/module/core/reflect_tools_meta"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/core/reflect_tools_meta"
description = """
Collection of mechanisms for reflection. Its meta module. Don't use directly.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

[lints]
workspace = true

[package.metadata.docs.rs]
features = [ "full" ]
all-features = false


[lib]
proc-macro = true

[features]

default = [
  "enabled",
  "reflect_derive",
]

full = [
  "default",
]
enabled = []
reflect_derive = []

[dependencies]
# iter_tools = { workspace = true, features = [ "full" ] }
# xxx : qqq : optimize features set

[dev-dependencies]
test_tools = { workspace = true }
