name : reflect_tools_meta

on :
  push :
    branches :
      - 'alpha'
      - 'beta'
      - 'master'


env :
  CARGO_TERM_COLOR : always

jobs :

  # reflect_tools_meta

  test :
    uses : Wandalen/wTools/.github/workflows/standard_rust_push.yml@alpha
    with :
      manifest_path : 'module/core/reflect_tools_meta/Cargo.toml'
      module_name : 'reflect_tools_meta'
      commit_message : ${{ github.event.head_commit.message }}
