name : minopengl

on :
  push :
    branches :
      - 'alpha'
      - 'beta'
      - 'master'


env :
  CARGO_TERM_COLOR : always

jobs :

  # minopengl

  test :
    uses : Wandalen/wTools/.github/workflows/standard_rust_push.yml@alpha
    with :
      manifest_path : 'module/blank/minopengl/Cargo.toml'
      module_name : 'minopengl'
      commit_message : ${{ github.event.head_commit.message }}
      commiter_username:  ${{ github.event.head_commit.committer.username }}
