name : test_experimental_a

on :
  push :
    branches :
      - 'alpha'
      - 'beta'
      - 'master'


env :
  CARGO_TERM_COLOR : always

jobs :

  # test_experimental_a

  test :
    uses : Wandalen/wTools/.github/workflows/standard_rust_push.yml@alpha
    with :
      manifest_path : 'module/test/a/Cargo.toml'
      module_name : 'test_experimental_a'
      commit_message : ${{ github.event.head_commit.message }}
