name : werror

on :
  push :
    branches :
      - 'alpha'
      - 'beta'
      - 'master'


env :
  CARGO_TERM_COLOR : always

jobs :

  # werror

  test :
    uses : Wandalen/wTools/.github/workflows/standard_rust_push.yml@alpha
    with :
      manifest_path : 'module/alias/werror/Cargo.toml'
      module_name : 'werror'
      commit_message : ${{ github.event.head_commit.message }}
