name : impls_index_meta

on :
  push :
    branches :
      - 'alpha'
      - 'beta'
      - 'master'


env :
  CARGO_TERM_COLOR : always

jobs :

  # impls_index_meta

  test :
    uses : Wandalen/wTools/.github/workflows/standard_rust_push.yml@alpha
    with :
      manifest_path : 'module/core/impls_index_meta/Cargo.toml'
      module_name : 'impls_index_meta'
      commit_message : ${{ github.event.head_commit.message }}
