name : former_types

on :
  push :
    branches :
      - 'alpha'
      - 'beta'
      - 'master'


env :
  CARGO_TERM_COLOR : always

jobs :

  # former_types

  test :
    uses : Wandalen/wTools/.github/workflows/standard_rust_push.yml@alpha
    with :
      manifest_path : 'module/core/former_types/Cargo.toml'
      module_name : 'former_types'
      commit_message : ${{ github.event.head_commit.message }}
