name : clone_dyn_meta

on :
  push :
    branches :
      - 'alpha'
      - 'beta'
      - 'master'


env :
  CARGO_TERM_COLOR : always

jobs :

  # clone_dyn_meta

  test :
    uses : Wandalen/wTools/.github/workflows/standard_rust_push.yml@alpha
    with :
      manifest_path : 'module/core/clone_dyn_meta/Cargo.toml'
      module_name : 'clone_dyn_meta'
      commit_message : ${{ github.event.head_commit.message }}
