name : test_tools

on :
  push :
    branches :
      - 'alpha'
      - 'beta'
      - 'master'


env :
  CARGO_TERM_COLOR : always

jobs :

  # test_tools

  test :
    uses : Wandalen/wTools/.github/workflows/standard_rust_push.yml@alpha
    with :
      manifest_path : 'module/core/test_tools/Cargo.toml'
      module_name : 'test_tools'
      commit_message : ${{ github.event.head_commit.message }}
